# Generated by Django 5.1.4 on 2024-12-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pro_code', models.TextField(blank=True, null=True)),
                ('bolum_adi', models.TextField(blank=True, null=True)),
                ('number_0_12_0_06_katsayı_ile_yerleşen_son_kişinin_başarı_sıras', models.TextField(blank=True, db_column='0,12 + 0,06 Katsayı ile Yerleşen Son Kişinin Başarı Sıras', null=True)),
                ('number_0_12_0_06_katsayı_ile_yerleşen_son_kişinin_puanı_field', models.TextField(blank=True, db_column='0,12 + 0,06 Katsayı ile Yerleşen Son Kişinin Puanı*', null=True)),
                ('number_0_12_katsayı_ile_yerleşen_son_kişinin_başarı_sırası_field', models.TextField(blank=True, db_column='0,12 Katsayı ile Yerleşen Son Kişinin Başarı Sırası*', null=True)),
                ('number_0_12_katsayı_ile_yerleşen_son_kişinin_puanı_field', models.TextField(blank=True, db_column='0,12 Katsayı ile Yerleşen Son Kişinin Puanı*', null=True)),
                ('obp_si_kırılarak_yerleşen_sayısı', models.TextField(blank=True, db_column="OBP'si Kırılarak Yerleşen Sayısı", null=True)),
                ('tavan_basari_sirasi_0_12_field', models.TextField(blank=True, db_column='Tavan_Basari_Sirasi_(0,12)', null=True)),
                ('tavan_puan_0_12_field', models.TextField(blank=True, db_column='Tavan_Puan_(0,12)', null=True)),
                ('boş_kalan_kontenjan', models.TextField(blank=True, db_column='Boş Kalan Kontenjan', null=True)),
                ('burs_türü', models.TextField(blank=True, db_column='Burs Türü', null=True)),
                ('ek_yerleşen', models.TextField(blank=True, db_column='Ek Yerleşen', null=True)),
                ('fakülte_yüksekokul', models.TextField(blank=True, db_column='Fakülte / Yüksekokul', null=True)),
                ('genel_kontenjan', models.TextField(blank=True, db_column='Genel Kontenjan', null=True)),
                ('genel_kontenjana_yerleşen', models.TextField(blank=True, db_column='Genel Kontenjana Yerleşen', null=True)),
                ('okul_birincisi_kontenjanı', models.TextField(blank=True, db_column='Okul Birincisi Kontenjanı', null=True)),
                ('okul_birincisi_kontenjanına_yerleşen', models.TextField(blank=True, db_column='Okul Birincisi Kontenjanına Yerleşen', null=True)),
                ('puan_türü', models.TextField(blank=True, db_column='Puan Türü', null=True)),
                ('toplam_kontenjan', models.TextField(blank=True, db_column='Toplam Kontenjan', null=True)),
                ('toplam_yerleşen', models.TextField(blank=True, db_column='Toplam Yerleşen', null=True)),
                ('yerleşenlerin_ortalama_diploma_notu', models.TextField(blank=True, db_column='Yerleşenlerin Ortalama Diploma Notu', null=True)),
                ('yerleşenlerin_ortalama_obp_si', models.TextField(blank=True, db_column="Yerleşenlerin Ortalama OBP'si", null=True)),
                ('yerleşip_kayıt_yaptırmayan', models.TextField(blank=True, db_column='Yerleşip Kayıt Yaptırmayan', null=True)),
                ('ösym_program_kodu', models.TextField(blank=True, db_column='ÖSYM Program Kodu', null=True)),
                ('üniversite', models.TextField(blank=True, db_column='Üniversite', null=True)),
                ('üniversite_türü', models.TextField(blank=True, db_column='Üniversite Türü', null=True)),
                ('i_lk_yerleşme_oranı', models.TextField(blank=True, db_column='İlk Yerleşme Oranı', null=True)),
                ('yil', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genel_bilgiler_last_2024',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HacettepeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('number', models.CharField(blank=True, null=True)),
                ('gecen_yildan_degisim', models.CharField(blank=True, null=True)),
                ('universite', models.CharField()),
                ('sehir', models.CharField()),
                ('fakulte_veya_bolum', models.CharField()),
                ('puan_turu', models.CharField(blank=True, null=True)),
                ('toplam_kontenjan_ve_gecen_yildan_farki', models.CharField(blank=True, null=True)),
                ('toplam_yerlesen', models.CharField(blank=True, null=True)),
                ('genel_kontenjan_en_dusuk_puan', models.CharField(blank=True, null=True)),
                ('genel_kontenjan_en_yuksek_puan', models.CharField(blank=True, null=True)),
                ('genel_kontenjan_en_dusuk_siralama_ve_bir_onceki_yildan_farki', models.CharField(blank=True, null=True)),
                ('empty_area1', models.CharField(blank=True, null=True)),
                ('empty_area2', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hacettepe_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HighSchoolTable',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pro_code', models.BigIntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('university', models.TextField(blank=True, null=True)),
                ('major_name', models.TextField(blank=True, null=True)),
                ('university_type', models.TextField(blank=True, null=True)),
                ('grade_type', models.TextField(blank=True, null=True)),
                ('scholarship_type', models.TextField(blank=True, null=True)),
                ('hihg_school', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('new_graduate', models.TextField(blank=True, null=True)),
                ('old_graduate', models.TextField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'high_school_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TercihSihirbazi',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('yop_kodu', models.TextField(blank=True, null=True)),
                ('universite', models.TextField(blank=True, null=True)),
                ('fakulte', models.TextField(blank=True, null=True)),
                ('program_adi', models.TextField(blank=True, null=True)),
                ('sehir', models.TextField(blank=True, null=True)),
                ('universite_turu', models.TextField(blank=True, null=True)),
                ('ucret_burs', models.TextField(blank=True, null=True)),
                ('puan_turu', models.TextField(blank=True, null=True)),
                ('ogretim_turu', models.TextField(blank=True, null=True)),
                ('yil', models.TextField(blank=True, null=True)),
                ('doluluk_statu', models.TextField(blank=True, null=True)),
                ('kontenjan', models.TextField(blank=True, null=True)),
                ('taban_puan', models.FloatField(blank=True, null=True)),
                ('tbs', models.TextField(blank=True, null=True)),
                ('yerlesen', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tercih_sihirbazi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwPreferenceTendencySamePrograms',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('üniversite', models.TextField(blank=True, db_column='Üniversite', null=True)),
                ('bolum_adi', models.TextField(blank=True, null=True)),
                ('pro_code', models.BigIntegerField(blank=True, null=True)),
                ('yil', models.BigIntegerField(blank=True, null=True)),
                ('program', models.TextField(blank=True, db_column='Program', null=True)),
                ('tercih_sayısı', models.TextField(blank=True, db_column='Tercih Sayısı', null=True)),
            ],
            options={
                'db_table': 'vw_preference_tendency_same_programs',
                'managed': False,
            },
        ),
    ]
